
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const $=id=>document.getElementById(id);
const jar=(t,s)=>`<svg viewBox="0 0 200 250" class="jar"><ellipse cx="100" cy="238" rx="70" ry="9" fill="#000" opacity=".5"/><rect x="28" y="46" width="144" height="188" rx="20" fill="url(#bd)"/><rect x="38" y="10" width="124" height="44" rx="10" fill="url(#gd)"/><rect x="28" y="92" width="144" height="100" fill="#0a0a0b"/><rect x="28" y="92" width="144" height="3" fill="#ff3347"/><rect x="28" y="189" width="144" height="3" fill="#ff3347"/><text x="100" y="140" text-anchor="middle" font-size="44" font-weight="900" fill="#fff" font-family="Cairo,Arial Black,sans-serif">JMK</text><text x="100" y="168" text-anchor="middle" font-size="13" fill="#ff6b78" letter-spacing="2.5" font-family="Cairo,sans-serif">${t}</text><text x="100" y="214" text-anchor="middle" font-size="10" fill="#aaa" font-family="Cairo,sans-serif">${s}</text><rect x="40" y="58" width="9" height="168" rx="4" fill="#fff" opacity=".08"/></svg>`;
let wa='',tab='all',idx={},sel={},C=[],op=false,P=[];
const isO=p=>+p.offer>0&&+p.offer<+p.price,cur=n=>(+n)+' ج.م',price=p=>isO(p)?+p.offer:+p.price,fls=p=>String(p.fl||'').split(',').map(s=>s.trim()).filter(Boolean);
const pic=u=>u==='hero.jpg'?'<div class="hp" style="background-image:url(hero.jpg)"></div>':`<img src="${esc(u)}" alt="">`,bgOf=u=>u==='hero.jpg'?"url('hero.jpg')":`url('${esc(u)}')`;
const card=(p,n)=>{const i=idx[p.id]||0,o=isO(p),w=p.name.split(' '),f=fls(p);return`<article class="card" style="--i:${n}">${o?`<span class="bdg">وفّر ${Math.round(100-p.offer/p.price*100)}%</span>`:''}<div class="im">${p.imgs[i]?pic(p.imgs[i]):jar(esc(w[0].toUpperCase().slice(0,10)),esc(w.slice(1).join(' ').slice(0,16)))}</div>${p.imgs.length>1?`<div class="th">${p.imgs.map((u,k)=>`<img src="${esc(u)}" class="${k===i?'on':''}" onclick="idx[${p.id}]=${k};site()">`).join('')}</div>`:''}<div class="bd"><h3>${esc(p.name)}</h3><p>${esc(p.d)}</p>${f.length?`<div class="fl">${f.map((x,k)=>`<button class="chip ${k===(sel[p.id]||0)?'on':''}" onclick="pick(this,${p.id},${k})">${esc(x)}</button>`).join('')}</div>`:''}<div class="pr">${o?`<b>${cur(p.offer)}</b><s>${cur(p.price)}</s>`:`<b>${cur(p.price)}</b>`}</div><button class="full" onclick="add(${p.id})">🛒 أضف للسلة</button></div></article>`};
function pick(b,id,k){sel[id]=k;[...b.parentNode.children].forEach((x,j)=>x.classList.toggle('on',j===k))}
function cnt(){document.querySelectorAll('.cn').forEach(e=>e.textContent=C.reduce((s,c)=>s+c.q,0))}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
function add(id){const p=P.find(x=>x.id===id);if(!p)return;const f=fls(p),fl=f.length?f[sel[id]||0]:'',k=C.find(c=>c.id===id&&c.fl===fl);k?k.q=Math.min(20,k.q+1):C.push({id,fl,q:1});cnt();toast('اتضافت للسلة ✓')}
function site(){const L=tab==='offers'?P.filter(isO):P,y=scrollY,s=P.find(p=>p.featured);document.documentElement.style.setProperty('--img',"url('"+((s&&s.imgs[0])||'hero.jpg')+"')");$('site').innerHTML=`<div class="ann">🚚 توصيل لحد بابك &nbsp;•&nbsp; 🏋️ استلام من الجيم &nbsp;•&nbsp; ✅ منتجات أصلية 100%</div><header class="nav"><div class="w nv"><a class="logo" href="#"><i>J</i>JMK</a><nav><a href="#p">المنتجات</a><a href="#sp">وصل حديثاً</a><a href="#h">طريقة الطلب</a></nav><button class="sm cb" onclick="op=true;cart()">🛒 السلة<span class="cn">0</span></button></div></header>
<section class="hero"><div class="w"><div class="hc"><span class="pill">${s?'🔥 وصل حديثاً — '+esc(s.name):'مكملات غذائية أصلية'}</span><h1>تمرين أقوى.<br><em>نتيجة</em> أسرع.</h1><p>مكملات JMK الأصلية بأسعار عادلة وعروض مستمرة. اختار نكهتك، ضيف للسلة، وأكّد طلبك على واتساب في دقيقة.</p><div class="cta"><a class="btn" href="#p">تسوّق الآن</a><a class="btn ghost" href="#sp">شوف الجديد</a></div><ul class="trust"><li>✓ أصلي 100%</li><li>✓ استلام من الجيم</li><li>✓ توصيل سريع</li></ul></div></div></section>
${s?`<section id="sp" class="w sec"><div class="spot"><div class="hp"></div><div><span class="pill">وصل حديثاً</span><h2 style="margin:12px 0">${esc(s.name)}</h2><p style="color:var(--m)">${esc(s.d)}</p><div class="sts">${(s.specs||'').split(',').filter(Boolean).map(x=>{const [a,b]=x.split(':');return`<div><b>${esc((a||'').trim())}</b><span>${esc((b||'').trim())}</span></div>`}).join('')}</div><div class="fl">${fls(s).map((x,k)=>`<button class="chip ${k===(sel[s.id]||0)?'on':''}" onclick="pick(this,${s.id},${k})">${esc(x)}</button>`).join('')}</div><div class="pr"><b>${cur(price(s))}</b>${isO(s)?`<s>${cur(s.price)}</s>`:''}</div><button onclick="add(${s.id})">🛒 أضف للسلة</button></div></div></section>`:''}
<section id="p" class="w sec"><div class="hd"><div><h2>منتجاتنا</h2><p>اختار اللي يناسب هدفك</p></div><div class="tabs"><button class="${tab==='all'?'on':''}" onclick="tab='all';site()">الكل</button><button class="${tab==='offers'?'on':''}" onclick="tab='offers';site()">🔥 العروض</button></div></div><div class="grid">${L.length?L.map(card).join(''):'<p class="empty">مفيش عروض دلوقتي، تابعنا قريب 🔥</p>'}</div></section>
<section id="h" class="w sec"><h2 style="text-align:center">اطلب في 3 خطوات</h2><div class="steps"><div><b>1</b><h4>اختار وضيف للسلة</h4><p>النكهة والكمية اللي تناسبك</p></div><div><b>2</b><h4>سجّل بياناتك</h4><p>الاسم والرقم وجيم أو توصيل</p></div><div><b>3</b><h4>أكّد على واتساب</h4><p>طلبك بيوصلنا وبنتواصل معاك فوراً</p></div></div></section>
<footer><div class="w ft"><a class="logo" href="#"><i>J</i>JMK</a><span>© 2026 JMK Supplements. جميع الحقوق محفوظة.</span></div></footer><a class="fab" href="https://wa.me/${esc(wa)}" target="_blank" rel="noopener" aria-label="واتساب">💬</a>`;cnt();scrollTo(0,y)}
const F={name:'',phone:'',type:'gym',address:''};
const items=()=>C.map(c=>({...c,p:P.find(x=>x.id===c.id)})).filter(c=>c.p),total=()=>items().reduce((s,c)=>s+price(c.p)*c.q,0);
function sv(){if($('fn')){F.name=$('fn').value;F.phone=$('fp').value}if($('fa'))F.address=$('fa').value}
function qty(i,d){sv();C[i].q+=d;if(C[i].q<1)C.splice(i,1);else C[i].q=Math.min(20,C[i].q);cnt();cart()}
function cart(msg){if(!op){$('m').innerHTML='';return}const I=items();$('m').innerHTML=`<div class="ov" onclick="op=false;cart()"><aside class="dr" onclick="event.stopPropagation()"><div class="dh"><h3>🛒 سلتك</h3><button class="s x" onclick="op=false;cart()">✕</button></div>${I.length?I.map((c,i)=>`<div class="it"><div class="th2" style="background-image:${c.p.imgs[0]?bgOf(c.p.imgs[0]):'none'}"></div><div class="ii"><b>${esc(c.p.name)}</b>${c.fl?`<small>${esc(c.fl)}</small>`:''}<span>${cur(price(c.p)*c.q)}</span></div><div class="st"><button class="s" onclick="qty(${i},-1)">−</button><b>${c.q}</b><button class="s" onclick="qty(${i},1)">+</button></div></div>`).join('')+`<label>الاسم<input id="fn" maxlength="60" value="${esc(F.name)}"></label><label>رقم الموبايل<input id="fp" inputmode="tel" maxlength="16" value="${esc(F.phone)}"></label><label>طريقة الاستلام</label><div class="row" style="margin-top:6px"><div class="opt ${F.type==='gym'?'on':''}" onclick="sv();F.type='gym';cart()">🏋️ استلام من الجيم</div><div class="opt ${F.type==='delivery'?'on':''}" onclick="sv();F.type='delivery';cart()">🚚 توصيل</div></div>${F.type==='delivery'?`<label>العنوان بالتفصيل<textarea id="fa" rows="3" maxlength="200">${esc(F.address)}</textarea></label>`:''}<div class="tot"><span>الإجمالي</span><b>${cur(total())}</b></div><button class="full" onclick="sendO()">إتمام الطلب على واتساب</button>${msg?`<pre>${esc(msg)}</pre><p class="note">معاينة فقط. في الموقع الحقيقي بيفتح واتساب برسالة زي دي على رقم ${esc(wa)}.</p>`:''}`:'<p class="empty" style="text-align:center">السلة فاضية، ضيف منتج وابدأ 💪</p>'}</aside></div>`}
function sendO(){sv();if(!F.name.trim()||!/^\+?\d{8,15}$/.test(F.phone.replace(/\s/g,''))||(F.type==='delivery'&&!F.address.trim()))return alert('كمّل البيانات صح');go(['🛒 طلب جديد - JMK',...items().map(c=>`• ${c.p.name}${c.fl?' ('+c.fl+')':''} × ${c.q} = ${cur(price(c.p)*c.q)}`),'الإجمالي: '+cur(total()),'الاسم: '+F.name,'الموبايل: '+F.phone,F.type==='delivery'?'توصيل: '+F.address:'استلام من الجيم'].join('\n'))}
const okImg=u=>/^(uploads\/[\w.-]+|hero\.jpg)$/.test(u);
function go(m){if(!wa)return alert('الطلب مش متاح حالياً');window.open('https://wa.me/'+wa+'?text='+encodeURIComponent(m),'_blank','noopener');C=[];op=false;cnt();cart()}
async function load(){try{const d=await(await fetch('data.json?'+Date.now())).json();wa=String((d.settings||{}).whatsapp||'').replace(/\D/g,'');
 P=(d.products||[]).map(p=>({id:+p.id,name:String(p.name||''),d:String(p.description||''),fl:String(p.fl||''),specs:String(p.specs||''),featured:!!p.featured,price:+p.price||0,offer:p.offerPrice==null?'':+p.offerPrice,imgs:(p.images||[]).filter(okImg)}))}catch(e){}
 site();$('site').classList.add('an');setTimeout(()=>$('site').classList.remove('an'),1200)}
$('site').innerHTML='<p style="padding:60px 20px;text-align:center;color:#999">جاري التحميل…</p>';load();
(function(){const l=document.createElement('link');l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;800;900&display=swap';document.head.appendChild(l)})();
